camunda.bpm:
  admin-user:
    id: mab
    password: mab
    firstName: Marc-Antoine
  filter:
    create: All tasks

camunda:
  bpm:
    auto-deployment-enabled: true

  external:
    tasks:
      polling-interval: 3000